### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Blash** [BGforgeNet/bg2-tweaks-and-tricks#33]
Hello!
I tried installing the latest version from the master branch (not "release") on an EET game, this is the outcome:

NOT INSTALLED DUE TO ERRORS No talking when hiding in shadows

NOT INSTALLED DUE TO ERRORS Potion of really mirrored eyes

NOT INSTALLED DUE TO ERRORS True true sight

NOT INSTALLED DUE TO ERRORS Sensible Otiluke's sphere

NOT INSTALLED DUE TO ERRORS Greater Command AoE

NOT INSTALLED DUE TO ERRORS Fair fights

NOT INSTALLED DUE TO ERRORS More map notes

C:\EET\00783>

ERROR: Sys_error("tnt/lib/bgforge/main.tpa: No such file or directory")
Extended Soundsets for NPC -> BG1 soundsets prevail (Tweaks-and-Tricks (new)) was not installed due to errors.

You can try to repair the problem and start the installation of the component again. In this case please select "retry" after the repair.

If you don't want to spent time for that now, you can also continue without the component or exit the program. The Setup will continue with the installation of that component.
Enter [r]etry, [c]ontinue or [e]xit.

**Comment by burner1024** [comment]
Hi. Branches are not supposed to be used directly, and installing them is not supported.
The cause of the error you got is missing [git submodule](https://github.com/BGforgeNet/BGforge-MLS-IElib).
