### ISSUE TITLE
tnt:10 failed install on EET via Project Infinity

### ISSUE THREAD

**Issue by 4udr4n** [BGforgeNet/bg2-tweaks-and-tricks#34]
tnt:10:Additions only failed to install: ERROR: Failure("resource [viconi61.cre] not found for 'COPY'")
This is the "Extended Soundsets for NPCs" that should merge soundset. Feels like this is EET related, but thought it worth reporting here.
[WeiDU.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/4550973/WeiDU.log)
[SETUP-TNT.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/4550979/SETUP-TNT.txt)

**Comment by burner1024** [comment]
Yes, I know about that. TnT wasn't supposed to be added to PI just yet, it needs some work. Only WMA is ready. @ALIENQuake.

**Comment by 4udr4n** [comment]
WMA?

**Comment by burner1024** [comment]
[Wild Mage Additions](https://github.com/BGforgeNet/bg2-wildmage)

**Comment by 4udr4n** [comment]
Ah, thanks.
For what it is worth, these components installed fine on EET:
tnt:16:No talking when hiding in shadows
tnt:35:GSPA + holding
tnt:39:Can't steal from fences
tnt:41:No XP farming
tnt:42:Improved strongholds

**Comment by ALIENQuake** [comment]
@burner1024 Ok, I will remove tnt from PI but I think that you should also rewrite ENGINE_IS conditions since `ENGINE_IS bg2ee` is also true for EET game.

**Comment by burner1024** [comment]
TnT and others (if any, can't check myself) please, for now only WMA should be enabled.

> you should also rewrite ENGINE_IS conditions since `ENGINE_IS bg2ee` is also true for EET game.

I don't see the issue, please elaborate.

**Comment by 4udr4n** [comment]
@ALIENQuake when you say remove from PI, what do you mean? I just download the mod zips, unzip to a folder and and point PI at my unzipped folder. Am I missing something?

**Comment by ALIENQuake** [comment]
> TnT and others (if any, can't check myself) please, for now only WMA should be enabled.
> 
> > you should also rewrite ENGINE_IS conditions since `ENGINE_IS bg2ee` is also true for EET game.
> 
> I don't see the issue, please elaborate.

If the mod doesn't support EET, it should not be able to install on EET. Using (NO GAME_IS eet) should be enough to prevent installation with an appropriate message like "This component doesn't' support EET yet"

> @ALIENQuake when you say remove from PI, what do you mean? I just download the mod zips, unzip to a folder and and point PI at my unzipped folder. Am I missing something?

'removed from PI' actually means "It will not show at Download Mods > BGForgeNet mod list", sorry for confustion.

**Comment by burner1024** [comment]
> If the mod doesn't support EET, it should not be able to install on EET. Using `REQUIRE_PREDICATE (NOT GAME_IS eet) @xxx` should be enough to prevent installation with an appropriate message like "This component doesn't' support EET yet"

Published releases are not to be altered. Unpublished ones are not to be used.
Current master installs [fine](https://golem.bgforge.net/logs/tweaks-and-tricks/141) on EET, but there are things to be done yet.

**Comment by ALIENQuake** [comment]
@burner1024 PI downloads latest release, not master, don't worry. Removing tnt from BGForgeNet mod list is not really good idea since the mod supports other games. How about we keep things as they are until TnT will support EET?

**Comment by burner1024** [comment]
But they don't have any required metadata.

**Comment by ALIENQuake** [comment]
Metadata is not required for PI to be able to install mods itself.

**Comment by burner1024** [comment]
I see. Still, too many people using EEs now, I'd prefer to not enable the mods until they are updated.

**Comment by ALIENQuake** [comment]
Yep, agree, will proceed.

**Comment by ALIENQuake** [comment]
The mod no longer appears on PI "Mods" list, will be re-added when it will be ready.

**Comment by burner1024** [comment]
Cool, thanks.
