### ISSUE TITLE
Better trap detection

### ISSUE THREAD

**Issue by Dredd893** [BGforgeNet/bg2-tweaks-and-tricks#35]
Hello,
I enjoy your mod and it is currently a stable addition to my modlist. I would like to ask if you could add another feature for the traps component: a way to make thieves detect traps instantly provided the got the skill, instead of having to wait X time. I don't have the technical prowess to make it myself, but I know how it could be done.

I would spawn a spy over the trap and force a modified Detect Traps with reduced radius to reveal it. Some traps however have pretty wild distance between their object's location (where OT text pops up) and their actual polygon, though, so there might be a few hiccups along the way.

**Comment by burner1024** [comment]
Well, that's very not PnP. And I'm not sure it's actually possible.
Do you mean to allow this while they are in detection mode or just free at any time?

**Comment by Dredd893** [comment]
Detection mode.

**Comment by burner1024** [comment]
I'll think and see what can be done, but can't promise anything.

> Some traps however have pretty wild distance between their object's location (where OT text pops up) and their actual polygon, though, so there might be a few hiccups along the way.

Some screenshots of this could be helpful.

**Comment by burner1024** [comment]
Something close enough to center point could probably be found with simply averaging all of boundary coordinates.
However find traps effect doesn't have a range parameter and the spell uses a range of 1, so it doesn't determine the actual range.
Anyone wants to test and report how far blind thieves can detect?

**Comment by burner1024** [comment]
If no one wants, I guess it not in great demand...

**Comment by Dredd893** [comment]
I didn't receive any notification you answered the prior messages. 
I actually checked here today by chance.

So... if you are still looking for help, I'm out there.

**Comment by burner1024** [comment]
> I didn't receive any notification you answered the prior messages.

Strange, you should've, as you're the author of the issue. You can verify that you're subscribed to the issue, and check spam folder.

> So... if you are still looking for help, I'm out there.

I think it is you who's looking for help :). I'm doing a feature freeze and want to release soon, but there's still time to squeeze in some changes.
So yes, I'm open to feedback yet.

**Comment by Dredd893** [comment]
When I said if you were looking for help, what I meant is that I'm missing what you are asking us to do. Are you looking 

1) for a screenshot of this "Some traps however have pretty wild distance between their object's location (where OT text pops up) and their actual polygon, though, so there might be a few hiccups along the way".

or
2) you wish us to check how far blind thieves can detect

or
3) something else?

**Comment by burner1024** [comment]
Both 1 and 2 could be helpful.

> If it's 2), how am I supposed to check it?

I think that's pretty straightforward? Get a thief, make him blind, go near a trap, try to detect it, note the range.

**Comment by burner1024** [comment]
...actually, on the second thought, modal state would still be subject to delay, and I don't know if it could be enforced. Please also test a blind **cleric** with Find Traps active.

**Comment by Dredd893** [comment]
2) No matter how near I am to the trap, I can't detect it if the thief is blind.
3) With the cleric I can detect it from pretty far, 

Some screenshots proving both the facts above: https://imgur.com/a/sthdyzk

**Comment by burner1024** [comment]
Hmm. That is unfortunate. I see no way to limit spell range... If forced on a spy, it would reveal all traps around, regardless of actual thief skill.
Any ideas?

**Comment by Dredd893** [comment]
Check what I found here:
https://forums.beamdog.com/discussion/71763/trap-detection-recovery-evasion

I guess I can close the issue? Thanks for your help!

**Comment by burner1024** [comment]
Indeed that looks interesting. It does use a custom pro, and it appears that a spy creature is not even necesary, something which I never considered.
Although sadly it doesn't work with classic editions. Still, I probably could steal some code from that. Thank you for sharing!
if that covers your needs, then this issue can stay closed.

**Comment by Dredd893** [comment]
I also play on classic - so I would like to have it on BG2:Trilogy. Give it a thought.

Cheers!

**Comment by burner1024** [comment]
OK, I found out it's doable, and actually isn't very hard.
However, I find myself drowning in the number of options. There are 6 subcomponents already, and with adding instant detection it could be times two at least (same things apply - range, action, combat state...).

So which (existing) subcomponents do you guys usually use? And what would be the ideal trap mechanic for you (sense, instant detection, automatically entering detection mode on sense, range of both, in/out of combat, displaying strings over head, displaying trap type in those strings, pauses, sounds, evasion, etc - everything already present in TnT and the other mod, and whatever else you can think of)?

(I know what I want, more or less, but I'd like to hear opinions to decide what to cut and what to include).

**Comment by Dredd893** [comment]
Personally I always use
"Increase trap sense range (default range is about half line of sight. This component increases it to LoS)"

I never found the other option useful even if I understand some may appreciate them.

**Comment by burner1024** [comment]
All right, through heinous engine abuse, employing lots of cursing and some ideas from the mod you linked, I managed to put together a version that should work on both CE and EE, and keeps all the important components.
Feel free to try it out:  [tnt_v8.beta.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/4840469/tnt_v8.beta.zip)

It's incompatible with other traps mods, of course. The changes will be visible only in yet unvisited areas. I do not recommend using in a playthrough just yet, better set up a copy installation and try it there (thankfully, the starting dungeon has a good amount of traps).

I would love to hear feedback about how it works in the wild, including both thief and cleric classes, various component combinations, rooms with multiple traps, multiple rogues in the party, any glitches and/or inconveniences that come up.

**Comment by Dredd893** [comment]
I feel very very happy for your release!

By chance, can you also publish this on other BG forums? I'm afraid I will be away for a bit and I won't be to give you the feedback you are looking for.

Also, I noticed you also support EE. Is your version of traps detection different from the one mentioned above?

**Comment by burner1024** [comment]
It's a pre-release. Release can wait a bit, it is not a problem.
Once it's released, you can create topics on the forums if you want to.
It is not the same as the other one, or it wouldn't be much point in making it. The doc is [here](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/blob/dev/docs/traps.md).
