### ISSUE TITLE
"Throwing Weapons Damage Type" error

### ISSUE THREAD

**Issue by ChitownWillie** [BGforgeNet/bg2-tweaks-and-tricks#36]
Installing on BGT with WeiDU 24700:

_Copying and patching 4014 files ...
ERROR: [AEGIS.ITM] -> [override/AEGIS.ITM] Patching Failed (COPY) (Not_found)
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Throwing weapons damage type -> Make axes slashing and hammers blunt], rolling back to previous state
Will uninstall   0 files for [TNT/TNT.TP2] component 26.
Uninstalled      0 files for [TNT/TNT.TP2] component 26.
ERROR: Not_found
Please make a backup of the file: SETUP-TNT.DEBUG and look for support at: https://github.com/BGforgeNet/bg2-tweaks-and-tricks/issues
Using Language [English]_

**Comment by burner1024** [comment]
Huh, there's no Aegis in your BGT?
Please attach the debug file. And try v246.

**Comment by ChitownWillie** [comment]
Hi,

Looks like "Aegis.itm" is located in "override" folder - Is that the
correct location?

Also, debug attached.

**Comment by burner1024** [comment]
Doesn't look like GH attached the file.
Location is correct.
What about v246?

**Comment by ChitownWillie** [comment]
Same result:

_WeiDU v 24600 Log

[./override/AEGIS.ITM] loaded, 562 bytes
ERROR: cannot convert off or %off% to an integer
ERROR: [AEGIS.ITM] -> [override/AEGIS.ITM] Patching Failed (COPY) (Not_found)
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Throwing weapons damage type -> Both of the above options], rolling back to previous state
Unable to Unlink [tnt/backup/27/OTHER.27]: Unix.Unix_error(1, "unlink", "tnt/backup/27/OTHER.27")
[tnt/backup/27/UNSETSTR.27] SET_STRING uninstall info not found
Will uninstall   0 files for [TNT/TNT.TP2] component 27.
Uninstalled      0 files for [TNT/TNT.TP2] component 27.
Unable to Unlink [tnt/backup/27/READLN.27]: Unix.Unix_error(20, "unlink", "tnt/backup/27/READLN.27")
Unable to Unlink [tnt/backup/27/READLN.27.TEXT]: Unix.Unix_error(20, "unlink", "tnt/backup/27/READLN.27.TEXT")_

**Comment by ChitownWillie** [comment]
[SETUP-TNT.DEBUG.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/5375026/SETUP-TNT.DEBUG.txt)

**Comment by burner1024** [comment]
I pushed a new version, should be good now.
