### ISSUE TITLE
Install order for Mega Mod installation

### ISSUE THREAD

**Issue by ChitownWillie** [BGforgeNet/bg2-tweaks-and-tricks#37]
[WeiDU.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/5375063/WeiDU.log)

Any recommendations? I installed just before "Worldmap" (i.e., after all other mods).

**Comment by burner1024** [comment]
You're good. The components that you have selected can go in pretty much any order.
Except for the store prices one, which obviousy should go after any mods that add stores.
