### ISSUE TITLE
"More ankheg armors by Taerom" vs CDTweaks' "Taerom Makes Additional Ankheg Armor"

### ISSUE THREAD

**Issue by ChitownWillie** [BGforgeNet/bg2-tweaks-and-tricks#39]
Seems like they're one-and-the-same:

Taerom Makes Additional Ankheg Armors (Icendoan/grogerson)
BGEE, EET, BG, BG2, BGT, Tutu

In the standard game, the smith Taerom will buy all the ankheg shells the party has at one time, and will make only one set of Ankheg Armor. After it is completed, he will not even buy ankheg shells. This tweak changes this. He will now buy one shell at a time, and will again buy shells and make additional armor once the first is completed. Cost and time requirements still apply, and he can only make one at a time. Fenten in Baldur's Gate will also buy shells one at a time.

**Comment by burner1024** [comment]
Probably.
Github is really for bug reports and/or specific feature requests.
Questions and discussions are better directed to the [forum](https://forums.bgforge.net/viewforum.php?f=31).
