### ISSUE TITLE
Effects of scrolls and potions do not stack with themselves only for BG2?

### ISSUE THREAD

**Issue by tomasz1986** [BGforgeNet/bg2-tweaks-and-tricks#40]
I have a question (or possibly a feature request?) regarding the "Effects of scrolls and potions do not stack with themselves" component.

Right now, the installation of this component is limited to BG2 only. Is it really applicable only to that game? I am asking, because I have removed the check and forcefully installed it in BG1EE. The installer did not report any problems.

Is there any technical reason why the component cannot be used in other games, and especially in the EE versions, as they all use the BG2 engine?

**Comment by burner1024** [comment]
No, there's no technical reason, it's probably historical. I think there was no EE when the component was first coded.
Re-checking it, it should work in EEs (BG saga), maybe IWD2 as well, but not classic IWD1/BG1. Not sure about IWDEE, as IESDP seems to be lacking its opcodes.

**Comment by tomasz1986** [comment]
Thank you for the quick fix.

It does seem to work in IWDee though? I have just tested by drinking multiple potions of genius, and they did not stack.

**Comment by burner1024** [comment]
ok, next release will allow IWDEE too. I'd include others, but I don't have all the games to test on, so feel free to report if any other should be included.
