### ISSUE TITLE
Unable to find ~%CLERIC_FIND_TRAPS%.spl

### ISSUE THREAD

**Issue by arosenow** [BGforgeNet/bg2-tweaks-and-tricks#42]
During the installation of the traps core the installation fails as it's unable to find ~%CLERIC_FIND_TRAPS%.spl
[SETUP-TNTDEBUG.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/5977316/SETUP-TNTDEBUG.txt)

**Comment by burner1024** [comment]
attach the log

**Comment by burner1024** [comment]
Hm, are you using zip release or PI, or other installation method?

**Comment by arosenow** [comment]
I used the "Download" button immediately below the list of files on git, it's a zip file version 8.6

**Comment by burner1024** [comment]
You downloaded source code.
Download zip with latest release instead https://github.com/BGforgeNet/bg2-tweaks-and-tricks/releases

**Comment by arosenow** [comment]
That's the file

**Comment by burner1024** [comment]
Can you try weidu 246?

**Comment by arosenow** [comment]
I tried it on a fresh install and it appears to work with the setup-tnt.exe provided. That version was stuck with 247 as it auto updated. 
The second language prompt didn't seem to come up in the 247 install, whilst it did for the clean install

**Comment by burner1024** [comment]
The language thing is normal during reinstallation, I think.

 You can run `setup-tnt.exe --noautoupdate` from cmd to skip automatic update.

**Comment by burner1024** [comment]
I think I found it.
Open `tnt/lib/bgforge/ids/main.tpp` in any text editor (notepad will work) and make the following [change](https://github.com/BGforgeNet/BGforge-MLS-IElib/commit/70b036bf5d80fd6004c6e20eae44de85da2fa4e2?branch=70b036bf5d80fd6004c6e20eae44de85da2fa4e2&diff=unified).

**Comment by arosenow** [comment]
It appears to have worked, glad we have people as dedicated as you working on making this classic better all the time
