### ISSUE TITLE
bloodless deeds

### ISSUE THREAD

**Issue by TotoR115** [BGforgeNet/bg2-tweaks-and-tricks#43]
There is an issu with the bloodless_deeds component and it makes a mess of nemphr.dlg.

I think that the following code line are needed before and after : 

DECOMPILE_DLG_TO_D
   REPLACE_TEXTUALLY CASE_INSENSITIVE EXACT_MATCH // bgt
   ...
COMPILE_D_TO_DLG

**Comment by burner1024** [comment]
You're right, must be a copy-paste typo. Fixed and released new, thanks.
