### ISSUE TITLE
Issues/nitpicks with starting bags component.

### ISSUE THREAD

**Issue by GraionDilach** [BGforgeNet/bg2-tweaks-and-tricks#45]
It assumes BGT areacode for Candlekeep which fails on Tutu (FW2600) and EET (BG2600).

https://github.com/BGforgeNet/bg2-tweaks-and-tricks/blob/master/tnt/components/starting_bags/main.tpa#L91-L92

It also doesn't play well with CDTweaks' Unique Containers solution although I'm not sure what to suggest to this one (it notably hands out the generic items).

**Comment by burner1024** [comment]
Yes, this is an old component, there was no EET back then, and I never used TuTu.
Doesn't Unique Containers automatically handle mod-added bags, though?

**Comment by GraionDilach** [comment]
It might do that via a static lookup although in that case it's probably an issue which should be reported there. I'll get back to you on that one.

**Comment by GraionDilach** [comment]
I think the way this work in TA is that it replaces the artwork on custom bags with unique ones and patches the mod-added ones to be unique. I'll provide the compat fix when TnT's component comes before TA. Thank you (and yes, I agree this ticket can be closed now)!
