### ISSUE TITLE
component #20 install fault

### ISSUE THREAD

**Issue by fritzkus** [BGforgeNet/bg2-tweaks-and-tricks#46]
framerate_check.tpa:
'wineconsole_rc' needs to be initialized outside ACTION_IF or the second ACTION_IF nested inside the first one:
```
//decompress to WAV
ACTION_IF NOT ~%WEIDU_OS%~ STR_EQ ~win32~ BEGIN
  AT_NOW wineconsole_rc ~wineconsole -h~ 
  ACTION_IF wineconsole_rc != 0 BEGIN 
    FAIL ~You must have wineconsole in PATH for this component~
  END
END
```
framerate.tpa:
Was missing '=' in line 28 an 29, corrected:
```
OUTER_SET wav_filesize_off = 0x4
OUTER_SET wav_datesize_off = 0x2a
```

**Comment by fritzkus** [comment]
Sorry for the bad formating...

**Comment by fritzkus** [comment]
I don't know, if on purpose but the master file ist missing all content inside lib\bgforge...

**Comment by burner1024** [comment]
it's connected as submodule

**Comment by burner1024** [comment]
should be working now
