### ISSUE TITLE
Installation issues on EET v2

### ISSUE THREAD

**Issue by oxygordian** [BGforgeNet/bg2-tweaks-and-tricks#48]
2.6 is mainstream, I'd say. Although older versions of SCS seem more stable in general (and require 2.5).

EET 2.6.6

c16:
Thanks for this, had the Viconia fix for EET but wasn't going to change the code to address .lua.
It has to be viconi6_ for bg1 - at least for me. (I'm new to modding/coding.)
I also had to toy around with the mod's folder structure to get component 16 to install.

c19 and 20:
20 installs but 19 fails with the error message: 

//processing WAVC file 'override\jaher35.wav'
//error: unrecognized file signature, must be 'WAVCV1.0'
//FAILURE:
//Failed to decompress jaher35 wavc

Also: the core component from traps fails to install if put very late (after SCS and other tweaks mods) but I don't have the error message, I think. 
Edit: found it. 
ERROR: [GT005.bcs] -> [override/GT005.bcs] Patching Failed (COPY) (Failure("Invalid spell number: -1"))
Stopping installation because of error.
ERROR: [AR3543.ARE] -> [override/AR3543.ARE] Patching Failed (COPY) (Failure("Invalid spell number: -1"))
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.
ERROR Installing [Improved trap detection: core (REQUIRED for any of previous traps components to work)], rolling back to previous state
Will uninstall 444 files for [tnt\tnt.tp2] component 14.
Uninstalled    444 files for [tnt\tnt.tp2] component 14.
ERROR: Failure("Invalid spell number: -1")

I think something is messing with my script files late in my install. That might also be the reason why EPS 6.4 won't install, but 6.3 does. Currently trying to figure out what's going on there.
My install order can be found here: 
https://github.com/oxygordian/EET-Install-Order

Btw: it would be neat, if the trap components of your mods would account for Thieving Skills for Bards - if that's possible at all. ; )

**Comment by burner1024** [comment]
Could you post your `GT005` script for review?

> it would be neat, if the trap components of your mods would account for Thieving Skills for Bards - if that's possible at all

Not sure what do you mean, bards can only pick pockets, what that has to do with traps?

**Comment by burner1024** [comment]
They converted wavc to ogg now... it's going to be more complicated to adjust sounds.
Did you actually see compliments in game? Classic can run with fps up to 90, but EEs are limited to 60. I wonder if you notice the overlap?

**Comment by oxygordian** [comment]
Thieving Skills for Bards is a mod (sorry that I wasn't clear on that front) which uses EEex to allow bards to use all thieving skills. (Including disarming traps.) https://github.com/Gibberlings3/Thieving-Skills-For-Bards

I'm using your mod alongside kjeron's trap overhaul which allows you to take the trap you disarmed with you, if your skill exceeds the DC by a certain margin. (among other things) The two mods seem to work alongside each other if one installs this mod after yours and chooses the right subcomponent. I thought I'd point that out as they can overlap and you might not be aware. The mod can be found obd Beamdog.

Ad compliments & insults:
I will have to check once I'm at my PC.
What I got from the code though (with my limited understanding) is that one would have to reinstall if the framerate changes, no?
There are mods (HiddenGameplayOptions) which offer a slider for changing the framerate without having to edit the .lua manually. It seems wise to have this component go very late then, if one wants to go from, say, 60 to 30 fps or something. I suppose you would have to resort to installing various versions of the files, but maybe that's a good approach.

Thanks for reacting so quickly!

**Comment by burner1024** [comment]
This is too much for one issue. You can file a separate issue for each problem that you encounter. For discussion, there's [forum](https://forums.bgforge.net/viewforum.php?f=31).

To look into the original issue, I'd like to see your `GT005`.

**Comment by burner1024** [comment]
`Invalid spell number` indicates that trap spell is missing from `spell.ids`, which means trap script won't work in the first place.
Nothing more to do here withough details.

**Comment by oxygordian** [comment]
Sorry, didn't have the time on my hands. 
Will provide you with more details when I get to doing so, can't offer a time frame as of now.

Will also split the ideas/"issues"/requests as you suggested.
Thanks for your support!

**Comment by burner1024** [comment]
> But I'm interested in a certain aspect/idea of UI: would it be possible to dynamically check for duplicate items (mod added as well) via descriptions/name/identical effects (last one might be prone to errors) and remove them?
Also giving optiond to leave items of protections etc. or rather all vanilla duplicates in an EET run untouched, as they might be needed for item upgrade mods.

Also, regarding item duplicates, it's a [separate mod](https://github.com/BGforgeNet/bg2-uniqueartifacts). Might be not exactly what you described, but pretty close I think.
