### ISSUE TITLE
'easy traps' invisible minion bug

### ISSUE THREAD

**Issue by Gwaihir5** [BGforgeNet/bg2-tweaks-and-tricks#49]
Hello. In my current playthrough, I found myself unable to leave an area (few dozens of 'you must gather your party' messages) or rest at an inn (party is scattered); in both cases, however, the party was definitely gathered.
This is caused by the global minion for autopause, which is somehow considered a party member.

More details in this thread: https://www.gibberlings3.net/forums/topic/33750-please-check-my-install-list-26-eet/page/6/#comment-305071

Is this something that can be fixed on an ongoing playthrough?

[WeiDU.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/7998790/WeiDU.log)

**Comment by burner1024** [comment]
It's a familiar, not a party member.
For a quick relief, open the savegame with NI and delete all the `g_traps1` cre's from it.
It shouldn't be happening, though. It's supposed to destroy itself immediately. Show the scripts attached to the cre and their contents.

**Comment by Gwaihir5** [comment]
This is the content of g_traps1.bcs:
`IF
	OnCreation()
THEN
	RESPONSE #100
		MakeGlobal()
		AddFamiliar()
		SmallWait(1)
END

`
it's the same in the mod folder (when downloaded, I mean) as when viewed in NI.

**Comment by burner1024** [comment]
attach a save game

**Comment by Gwaihir5** [comment]
[BALDUR.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/7998880/BALDUR.zip)

**Comment by burner1024** [comment]
the rest of the files in save too

**Comment by Gwaihir5** [comment]
Sorry XD

[000000001-Eoghan-Quick-Save-4.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/7998898/000000001-Eoghan-Quick-Save-4.zip)

**Comment by burner1024** [comment]
Did you install the mod mid-game or something?

**Comment by Gwaihir5** [comment]
No. I pasted this list of components into Project infinity in the order displayed:
[NEW_EET_INSTALL_v1.docx](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/7999065/NEW_EET_INSTALL_v1.docx)

**Comment by burner1024** [comment]
Well, adding this to the script should at least allow you to rest and leave the area
```
IF
  True()
THEN
  RESPONSE #100
    Wait(3)
    DestroySelf()
END
```
But I'm not sure how you got into this situation.

**Comment by Gwaihir5** [comment]
Thank you. 
If I may, this bit of code is not present even inside the g_traps1.baf before installation. Should be?

**Comment by Gwaihir5** [comment]
Sorry, didn't see your questions. It happened in Beregost, trapped chest inside middle bottom house. Mod works fine, with autopause and all: Imoen finds trap, display message. Later, I can't exit area, can't rest. Took a while, but eventually found out that hitting Tab shows 'uninjured' over an invisible creature. Which led me here.

**Comment by burner1024** [comment]
No, it shouldn't be present before installation.

> hitting Tab shows 'uninjured' over an invisible creature

Show a screenshot?

**Comment by Gwaihir5** [comment]
![Immagine 2022-02-04 020210](https://user-images.githubusercontent.com/96683286/152455088-8c952c43-821c-4ed2-bc06-b10c505c732b.jpg)

This is what happens if I drag-select the minion and make him talk with someone:
![Immagine 2022-02-03 215316](https://user-images.githubusercontent.com/96683286/152455159-bff34e22-1eb1-4b46-9d8d-c6544f27b558.png)

**Comment by Gwaihir5** [comment]
By the way, the code you gave me worked. The invisible minion disappears correctly, and I can travel normally.

**Comment by burner1024** [comment]
Not sure if autopause will work with it, though. If not, you can remove the code and see if you hit the issue again. Need a reliable way to reproduce this.

**Comment by Gwaihir5** [comment]
The issue came up all the time when I was testing multiple saves earlier, now I tried removing the code and it reappeared immediately. Doesn't matter if autopause is on or off. The pause at least worked well.

**Comment by Gwaihir5** [comment]
Autopause seems to work well with the fix too.

**Comment by oxygordian** [comment]
Gwaihir and me talked about it on G3. I obseverd aforementioned behaviour after Beregost (first trap?) and noticed said invisible familiar.
First I thought it hailed from a familiar component.
I subsequently discarded the traps auto-pause component a few weeks ago as it (?) is available as a basal option in my EET game. Maybe I'm missing a point here in conjunction with the mod's functions.
Thus I couldn't/didn't test this further.

Btw: sorry, that I didn't follow up on the other issue, didn't have the time. Did post there though.
Will do split issues or created a thread.
Thanks for your great support! 
Would be glad to provide feedback on EET/cross-mod compatibility once I find the time.

**Comment by Gwaihir5** [comment]
So I had the same issue again. This time it was related to the familiar created by g_traps1.cre. Since last time I had to reinstall the game twice for various reasons, with minimal component changes. I always added the code in this thread to g_traps1.bcs, but in my current playthrough I still had the message 'you must gather...' after finding the first trap in beregost. 
I was able to fix this by adding `RemoveFamiliar()` to the code, after looking among the files here on github. So all's good now, it's just super weird that it was working before without that line, and now it's required.


[WeiDU.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8143799/WeiDU.log)
[000000054-After the issue.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8144118/000000054-After.the.issue.zip)

**Comment by burner1024** [comment]
I reverted the script to use a party member for pausing.
It's less convenient (pause may interrupt player-issued orders, though it hardly happens often), but at least it doesn't have the save/load issue.
I might revisit this later, but for now don't have much time.

> I subsequently discarded the traps auto-pause component a few weeks ago as it (?) is available as a basal option in my EET game. Maybe I'm missing a point here in conjunction with the mod's functions.

The added autopause is on intuition trigger, not on trap found event. These are different.

**Comment by tehmasterer** [comment]
The new release seemed to fix the issue. I played for 2 hours the other night without encountering the bug. Thanks!

Just to add, I never had the **autopause** component installed. I had autopause enabled in the **game settings**. Maybe that caused a conflict?

**Comment by burner1024** [comment]
> Just to add, I never had the autopause component installed. I had autopause enabled in the game settings. Maybe that caused a conflict?

It certainly didn't, they are completely unrelated. So it's strange, but I'm glad it's working well for you.
