### ISSUE TITLE
EET 2.6.6, PI 0.9.9 on Win10: tnt:19;Tweaks and Tricks - Reintroduce and adjust to framerate 

### ISSUE THREAD

**Issue by oxygordian** [BGforgeNet/bg2-tweaks-and-tricks#50]
When trying to install the updated version of the component (WeiDU 249), it "explodes in my face" with non-standard letters/signs and goes on seemingly infinitely (what kind of code/language is that?) - an excerpt:
þÉýW”jÐTÒ }éP¾þ^ú›úQý'ýø¾ë
![tnt](https://user-images.githubusercontent.com/97057489/152637064-3600fc5f-f325-437d-8ce6-d89e0f836f17.jpg)

Update: Also happens with WeiDU 249/247. Tried vanilla EET as well. It installs with the included installer but shows same behaviour and hangs WeiDU. I didn't check whether it works ingame. 
Currently trying to figure out the issue, or rather Alien is.

**Comment by burner1024** [comment]
That's a screenshot of what?
Do you have debug log?

**Comment by oxygordian** [comment]
This is a screenshot of the debug log.
I can attach a debug log (I force quit though) - it is ~10MB.

**Comment by burner1024** [comment]
Yeesh, oggdec works differently on windows, so it just dumped wav into stdout.
