### ISSUE TITLE
"Fair fights -> Just a few selected enemies" installs with a warning | EET 2.6.6 - component 58

### ISSUE THREAD

**Issue by oxygordian** [BGforgeNet/bg2-tweaks-and-tricks#51]
Installs with the following warning:

//Installing [Fair fights -> Just a few selected enemies] [v8.14]
//Clearing the arrays.
//Clearing the variables.
//Clearing the inlined files.
//Clearing the macros.
//Clearing the IDS map.
//Appending to files ...
//Appending to files ...
//Clearing the IDS map.
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Compiling 1 dialogue file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//Copying and patching 1 file ...
//WARNING: cannot find block matching [.../tnt-inlined/fair_fights/dukes.baf]
//Copying and patching 1 file ...
//WARNING: cannot find block matching [.../tnt-inlined/fair_fights/dukes.baf]
//INSTALLED WITH WARNINGS     Fair fights -> Just a few selected enemies
//
//WARNING: tnt : 58 has encounter errors durring installation, exited with ExitCode = 3
//WARNING: unpausing installation will continue from next component

Suggestion:
It would be great to have a subcomponent with just the "innocent no more" ones. Also SCS touches Kahrk, I think. Can fork and comment out of course, but I'm very fresh to all of this.

**Comment by burner1024** [comment]
Not so sure about only innocent.
Don't know how it's related that SCS touches Kahrk.
Warning is fixed.
