### ISSUE TITLE
Trap type floaters appear for less than a second | EET 2.6.6, component 4

### ISSUE THREAD

**Issue by oxygordian** [BGforgeNet/bg2-tweaks-and-tricks#52]
Trap type floaters appear for less than a second - regardless of game fps setting.

**Comment by burner1024** [comment]
do you have script fix applied from #49?

**Comment by oxygordian** [comment]
No, I used latest release.

**Comment by burner1024** [comment]
I think that's pretty much how it's supposed to work. Share a video or gif.

**Comment by oxygordian** [comment]
Video as requested:
https://easyupload.io/cb9fk0

**Comment by burner1024** [comment]
Yeah, no, it's too fast. Did it always work for you this way?

**Comment by oxygordian** [comment]
I'm new to EET and modding so I never used it before. But from my ~1m old experience, yes.
I suppose you don't have EET as a platform to test on. If you can't remedy that, I can provide you with further testing, if needed.
Pertains to other components as well.

**Comment by burner1024** [comment]
I doubt it's related to EET. More likely, EE engine has different implementation of `DisplayStringHead`.

**Comment by oxygordian** [comment]
Yea, tested with pure vanilla EET and EET_end installed, same result.
