### ISSUE TITLE
crossmod compatibility: Trap components when used in conjunction with Bards being able to find traps

### ISSUE THREAD

**Issue by oxygordian** [BGforgeNet/bg2-tweaks-and-tricks#53]
https://www.gibberlings3.net/forums/topic/34217-skills-and-abilities-mod-alpha-release/
and
https://www.gibberlings3.net/files/file/1032-thieving-skills-for-bards/

open up trap finding/disarming to Bards (the latter to Rangers as well, iirc).
Would it be possible for TnT to check for them being installed (or maybe even better: provide all classes with the script, before these mods/future mods are installed) and extend the functionality to Bards?
They state that something is off, but don't search automatically and if you manually toggle, the search takes the normal, long, amount of time.

Does this script work with other scripts being active?
Say https://www.gibberlings3.net/mods/other/enhanced-powergaming-scripts/

Everything seems to work fine with thieves on EET 2.6, apart from trap type floaters, as mentioned. (they cycle: being displayed for ~0.2s and then a break for several s)
I did not test auto-pause (invis ally), as EET(?) provides this function per default.

**Comment by burner1024** [comment]
One of the mods is deprecated, I added support for the other.
Not sure how to check for all classes, but bards and rangers are in.
Scripts don't interfere with other scripts.
Autopause is different from trap found autopause.
