### ISSUE TITLE
Save Melicamp: Melicamp does not polymorph back to human

### ISSUE THREAD

**Issue by fritzkus** [BGforgeNet/bg2-tweaks-and-tricks#54]
Somehow this from your mods baf:
`		ActionOverride("Melicamp", Polymorph(MAGE_MALE_HUMAN_LOW))
`
translates to this in my games bsc:
`		ActionOverride("Melicamp",Polymorph(FIRE_RING))
`
Changelog-Dateien:
[thalantr.bcs-WeiDU-FileChangelog-2022-Feb-26.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8147485/thalantr.bcs-WeiDU-FileChangelog-2022-Feb-26.txt)
[THALANTR.00001.BCS.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8147486/THALANTR.00001.BCS.txt)
[THALANTR.00002.BCS.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8147487/THALANTR.00002.BCS.txt)
[THALANTR.00003.BCS.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8147488/THALANTR.00003.BCS.txt)
[THALANTR.00004.BCS.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8147489/THALANTR.00004.BCS.txt)
[THALANTR.00005.BCS.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8147490/THALANTR.00005.BCS.txt)

**Comment by burner1024** [comment]
It's likely related.
But why are you using old IA? I think it was updated some time ago.

**Comment by burner1024** [comment]
I'm not really sure why IA does this, anyway. Why delete an IDS symbol, I think there's no limit on IDS.
But also not sure if `MAGE_MALE_HUMAN_LOW` is effectively any different from `MAGE_MALE_HUMAN`.
@GwendolyneFreddy do you have any insight by chance?

**Comment by fritzkus** [comment]
IA v5 beta is the most recent version, I could find. There were talks about a new version (v6) here
[http://www.shsforums.net/topic/60391-so-the-infinity-animation-update/page-2](url)
but no release yet:
[(https://github.com/GwendolyneFreddy/Infinity-Animations)](url)
The new readme (v6.0.0) still links to download here:
[http://www.shsforums.net/files/file/859-ia-infinity-animations-core-mod-weidu-beta-5/](url)

Do you happen to have a more recent version?

**Comment by burner1024** [comment]
No... I thought it was already released.

**Comment by burner1024** [comment]
Anyway, if you change it to `MAGE_MALE_HUMAN`, does it work fine?

**Comment by fritzkus** [comment]
Yes, it does.

**Comment by burner1024** [comment]
Good. Could you share your weidu.log and tnt install log (tnt.debug or setup-tnt.debug) for review?

**Comment by fritzkus** [comment]
Here is my WeiDU.log:
[WeiDU.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8172563/WeiDU.log)
I don't think, that my setup-tnt.debug is of any help, only the last installed component is recorded (probably, because I used PI for installation?):
[Setup-tnt.debug.txt](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/8172578/Setup-tnt.debug.txt)
