### ISSUE TITLE
Not working with Linux

### ISSUE THREAD

**Issue by tehmasterer** [BGforgeNet/bg2-tweaks-and-tricks#58]
Trying to install this mod with BG2EE. I want the instant trap detection part of the mod.

I already have Tweaks Anthology, G3 Anniversary, and some scripts installed via WeiDU.

Running `weinstall tweaks-and-tricks-v8.16/`: Error: Failure("ERROR: TP2 file not found.")

I moved the **tnt** folder outside of tweaks-and-tricks-v8.16 into my main directory. I was able to install the mod, however I ran into many issues in-game. I was not able to leave/change districts in Athkatla, rest in inns, or enter certain buildings. I assume this is because the mod did not install properly, though it gave no errors on completion.

**Comment by burner1024** [comment]
Try uninstalling the autopause component.

**Comment by burner1024** [comment]
Also see #49

**Comment by tehmasterer** [comment]
> Try uninstalling the autopause component.

I never installed the autopause component. I had autopause on trap detection checked in the **game settings**, if that matters.

Can you comment on the Linux install method? Is the **tnt** folder suppose to moved outside tweaks and tricks, into the main BGEE directory?

**Comment by burner1024** [comment]
The [releases](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/releases) do not include a` tweaks-and-tricks-vX` directory.
You either have downloaded code as zip, or your extraction method is playing tricks on you.
```
$ 7z l tweaks-and-tricks-v8.17.zip | grep -v /

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=es_ES.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (406E3),ASM,AES-NI)

Scanning the drive for archives:
1 file, 6494028 bytes (6342 KiB)

Listing archive: tweaks-and-tricks-v8.17.zip

--
Path = tweaks-and-tricks-v8.17.zip
Type = zip
Physical Size = 6494028

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2021-11-22 00:34:08 .....      7951216      1269936  setup-tnt
2022-03-07 13:51:04 .....           55           55  setup-tnt.command
2021-11-21 19:10:48 .....      1364992      1265592  setup-tnt.exe
2022-03-07 13:50:59 D....            0            0  tnt
------------------- ----- ------------ ------------  ------------------------
2022-03-07 13:51:04           17645088      6398500  417 files, 99 folders
```

For clarity, yes, `tnt` dir is supposed to be in the main game dir.

**Comment by ahungry** [comment]
Never use a trailing slash on `weinstall` on Linux either, it has caused weird file not found issues for me - just use `weinstall tnt`, not `weinstall tnt/`
