### ISSUE TITLE
BAND is used instead of a BOR

### ISSUE THREAD

**Issue by GraionDilach** [BGforgeNet/bg2-tweaks-and-tricks#59]
Unless I'm overlooking something this wants to be a binary OR, since a binary AND destroys all other options in the header.

https://github.com/BGforgeNet/bg2-tweaks-and-tricks/blob/master/tnt/components/throwing_damage/main.tpa#L31

Note that this also breaks the feature on the EEs (if I read that right that it only sets a single bit) because the EEs split the strength bonus to two; see bottom of https://gibberlings3.github.io/iesdp/file_formats/ie_formats/itm_v1.htm.

**Comment by burner1024** [comment]
Looks like it's should be BOR, yes.
Does EE ignore bit0 altogether?

**Comment by GraionDilach** [comment]
Apparently yes, because I found this out only because Elestan at the Infinity Engine discord noticed that the end result does leads to him lacking strength bonus on thrown weapons.

**Comment by burner1024** [comment]
Splitting them makes sense, THAC0 for throwing should be governed by Dex. I think I'll use bit0 for Classic and bit3 for EE.
