### ISSUE TITLE
Improved Stronghold v8.19 install failure

### ISSUE THREAD

**Issue by Oloriniel** [BGforgeNet/bg2-tweaks-and-tricks#62]
[ProjectInfinity-WeiDU-Error-tnt-65.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/9127528/ProjectInfinity-WeiDU-Error-tnt-65.log)

**Comment by burner1024** [comment]
Uhm, what's your game platform? And weidu.log?

**Comment by GraionDilach** [comment]
I presume https://www.gibberlings3.net/forums/topic/35798-mod-orderfeedback-request/page/5/#comment-313240

**Comment by burner1024** [comment]
can't do anything without more info
