### ISSUE TITLE
Mod Romance Cheats v8.19 install failure

### ISSUE THREAD

**Issue by Oloriniel** [BGforgeNet/bg2-tweaks-and-tricks#63]
[ProjectInfinity-WeiDU-Error-tnt-70.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/9127533/ProjectInfinity-WeiDU-Error-tnt-70.log)

**Comment by burner1024** [comment]
attach your `nalia.bcs` and `baldur.bcs`

**Comment by burner1024** [comment]
zip them

**Comment by burner1024** [comment]
can't do anything without more info
