### ISSUE TITLE
Request: Compatibility with other familiar mods

### ISSUE THREAD

**Issue by Endarire** [BGforgeNet/bg2-tweaks-and-tricks#64]
Greetings, @burner1024!

We like the familiar tweaks in this mod but also know that familiar changes tend to overwrite each other from mods.  These mods each change familiars.  Adding these functionalities into your mod and letting users choose which options they like seems best from a technical perspective.

-Enhanced Edition Trilogy AKA EET (https://github.com/Gibberlings3/EET/releases)
EET changes familiars to accommodate casters of all levels.

-Klatu's Tweaks (http://www.shsforums.net/topic/57873-mod-klatu-tweaks-and-fixes/)
Adds the ability in EE games for familiars to sort scrolls in inventory.

-More Style for Mages (https://forums.beamdog.com/discussion/18108/mod-more-style-for-mages-v1-56/p1)
Adds choose-your-own-familiar, classed familiars (Mages & Thieves), and familiars for NPCs.  (This means vanilla NPC arcane casters and Humans can each have their familiar in addition to the main character.)  In one of the newest replies in this thread as of this writing is a link to a more updated EET version, though that version only has NPC familiars for Edwin.

-Tome & Blood AKA T&B (https://github.com/subtledoctor/TomeAndBlood)
Adds choose-your-own-familiar with extra bonuses to the master if the familiar is outside the pack.  Familiars also grant their master a 10% HP while summoned instead of a flat HP bonus.

Thankee!

**Comment by burner1024** [comment]
I'll take a quick look, but can't promise anything.

**Comment by burner1024** [comment]
I think EET tweaks and Klatu's should be compatible.
MSFM is a bit too complicated for me to get on with on my own. Maybe with @Renegade0's help. (Also, see https://github.com/Renegade0/msfm/issues/7)
TnB has more moderate changes, but still would be easier with @subtledoctor's input.

For now, not planning to do anything.
