### ISSUE TITLE
In an EET install, I think the invisible trap finder is causing the party to be unable to zone out of BG5400.are (nashkel mines)

### ISSUE THREAD

**Issue by ahungry** [BGforgeNet/bg2-tweaks-and-tricks#65]
I think I can track the following issue to this tweak pack, and more specifically, the traps component.

When I play as a character capable of summoning a familiar, and I go to BG5400.are (Nashkel mines, outer) and then zone into BG5401.are (Nashkel mines L1) and back out again, I'm unable to leave BG5400.are ("You must gather your party before venturing forth").   If I play as a non-familiar summoning class, this will not occur.

This happens even when I have no other party members, and have never summoned a familiar, however it only occurs about 50% of the time - I'm not sure if there is a race condition or timing issue (or if it's only possible due to the large amount of other mods I have installed).

When I remove TNT, I cannot reproduce this issue.

I've been comparing some game saves I have with and without this bug, and the common factor seems to be a `*_traps1` creature in my global creature set on the borked game, and none on the working games (as well as a `g_traps_minion_pause` variable).

I looked for the enemies and allies setting, and I don't see this invisible doomguard "traps" creature flagged as 3 (Familiar) but iirc he was Neutral or Ally, yet it still seems to trigger the type of check as if I needed to get my familiar closer to my party.

I couldn't affirm my suspicion by editing the save and removing the creature and variable, as doing so would cause a segfault on subsequent loading of the game.

If it matters or is relevant, I'm playing BG:EE and BG2:EE with SOD on GNU/Linux via the native binaries, in an EET setup.

I might have been able to debug further if I changed the invisible trap npc to a visible one?  Then I could at least see if he would let me zone out if he were somehow movable/able to be added to the party temporarily (or a way to auto-kill him to get him out of my living global creatures), however I'm not sure if there is even intended to be any support for this under EET or how often (if at all) this is still being maintained.

**Comment by burner1024** [comment]
Which version do you run?

**Comment by ahungry** [comment]
2.6 from Steam for BG:EE, SOD, BG2:EE

**Comment by burner1024** [comment]
I mean mod version.

**Comment by ahungry** [comment]
tweaks-and-tricks-v8.13.zip caused the issue - I see I'm a little behind (oops) - were any changes to the trap component done between then and now?  (last year Nov) - if so, I can re-test with the latest version

**Comment by burner1024** [comment]
Yes, there were.
I would be very careful about updating mid-game. Could make matters worse.

As for crash after removing the creature, I assume you use NI for that? I'd open an issue in the corresponding repo.

**Comment by ahungry** [comment]
Thanks @burner1024  - I am mid-reinstall (clean wipe + redo components) - I'll try adding the latest tnt and see how it goes.
