### ISSUE TITLE
Aldeth Sashenstar uses MAGE04 as key to Merchants Leauge Headquarters door

### ISSUE THREAD

**Issue by GaxGuy** [BGforgeNet/bg2-tweaks-and-tricks#66]
MAGE04.ITM is the key to Door0127.  Aldeth Sashenstar has one of those items to open the door (if other conditions are met) for the party to help him out with his bean counter problem.  Removing MAGE04 item from him in the Fair Fights component prevents him from being able to unlock that door.

**Comment by burner1024** [comment]
Thank for investigating.
