### ISSUE TITLE
Tactics Remix for EE(T)

### ISSUE THREAD

**Issue by Endarire** [BGforgeNet/bg2-tweaks-and-tricks#67]
Greetings, all!

[Tactics Remix](https://www.gibberlings3.net/forums/topic/35950-tactics-remix/) changes the BG1 Drizzt fight (and may be en route to changing Drizzt in BGII).  I mention this here to ensure everything is compatible.

Thankee!

**Comment by burner1024** [comment]
I wouldn't know, but if there's an incompatibility, feel free to report it.
