### ISSUE TITLE
Do you accept translation update via pull requests?

### ISSUE THREAD

**Issue by abalabokhin** [BGforgeNet/bg2-tweaks-and-tricks#68]
Hi, I tried to send pull request with Russian translation some time ago but at that time you said that any translation should be updated using translation system: https://hive.bgforge.net/projects/infinity-engine/tweaks-and-tricks/.

It seems that no translation but English was finished using this system and I hoped that you reconsider and can accept pull requests.

Thank you for your mod.

**Comment by burner1024** [comment]
There were some changes. Theoretically, it should be possible now, although I still don't like it and don't recommend it.
However, for the first pull you'll need to load the translation into corresponding PO using [msg2po](https://github.com/BGforgeNet/msg2po) toolset.

**Comment by abalabokhin** [comment]
I will try to figure out how to use the tool. Can you add iconv into the repo and change tp2 to use it, please? Without this changes Russian (and probably some other languages won't work. I can send you dedicated pull requests with these changes if you like.

**Comment by burner1024** [comment]
What do you mean by don't work?
Yes, if you send pull requests, please make them separate, one per issue, and include in the description what does that fix and how to reproduce that issue, so it can be verified.

**Comment by abalabokhin** [comment]
I created pull request and tried to answer the question what didn't work: https://github.com/BGforgeNet/bg2-tweaks-and-tricks/pull/69

**Comment by abalabokhin** [comment]
I tried to install msg2po with `pip3 install msg2po`, but I have the error:
```
 ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2857, in get_entry_map
    ep_map = self._ep_map
  File "/usr/lib/python3/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 461, in run
    installed = install_given_reqs(
  File "/usr/lib/python3/dist-packages/pip/_internal/req/__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 790, in install
    install_wheel(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/install/wheel.py", line 727, in install_wheel
    _install_wheel(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/install/wheel.py", line 561, in _install_wheel
    console, gui = get_entrypoints(distribution)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/install/wheel.py", line 121, in get_entrypoints
    for entry_point in dist.iter_entry_points():
  File "/usr/lib/python3/dist-packages/pip/_internal/metadata/pkg_resources.py", line 169, in iter_entry_points
    for group, entries in self._dist.get_entry_map().items():
  File "/usr/lib/python3/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2859, in get_entry_map
    ep_map = self._ep_map = EntryPoint.parse_map(
  File "/usr/lib/python3/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2535, in parse_map
    maps[group] = cls.parse_group(group, lines, dist)
  File "/usr/lib/python3/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2513, in parse_group
    ep = cls.parse(line, dist)
  File "/usr/lib/python3/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2491, in parse
    raise ValueError(msg, src)
ValueError: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'bgforge-config=msg2po.bgforge-config:main')

```
Is it my error (linux, python3) or a general error?

**Comment by burner1024** [comment]
I pushed a new version, try that.
If still doesn't work, please open an issue in that repo.

**Comment by abalabokhin** [comment]
It works now, thank you. So, I ran poify.py from tra dir on updated Russian tra files: `./poify.py ./russian`, it had some troubles with creating po/russian.pot after processing all tra files:
```
Traceback (most recent call last):
  File "/home/paladin/source/bg2-tweaks-and-tricks_new/tnt/tra/./poify.py", line 151, in <module>
    main()
  File "/home/paladin/source/bg2-tweaks-and-tricks_new/tnt/tra/./poify.py", line 147, in main
    poify(poify_dir)
  File "/home/paladin/source/bg2-tweaks-and-tricks_new/tnt/tra/./poify.py", line 110, in poify
    old_po = polib.pofile(dst_file)
  File "/home/paladin/.local/lib/python3.10/site-packages/polib.py", line 130, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/home/paladin/.local/lib/python3.10/site-packages/polib.py", line 78, in _pofile_or_mofile
    instance = parser.parse()
  File "/home/paladin/.local/lib/python3.10/site-packages/polib.py", line 1428, in parse
    raise IOError('Syntax error in po file %s(line %s)' %
OSError: Syntax error in po file (line 1)
```
However, after I created empty po/russian.pot file the script worked. I attached the produced russian.pot file here, but I can send it as a pull request with or without updated tra files.
[russian.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/10775494/russian.zip)

**Comment by burner1024** [comment]
`poify` creates a `POT` (`PO` Template) from source language. Which is English in this case. POT does not contain translations, it's only used to update PO files, which are actual translations.
To load translations from `tra` into `PO` you need `dir2msgstr`.
Although, looking at it now, the action has dir2msgstr enabled in this repo, so it might work if you just push the tras. Provided that it's all correct, syntax good, matches latest master, etc.

**Comment by abalabokhin** [comment]
I wasn't able to figure out how to use dir2msgstr, but if sending updated tra files should work I sent a pull request:
https://github.com/BGforgeNet/bg2-tweaks-and-tricks/pull/70, hopefully it will work.

**Comment by burner1024** [comment]
```
$ dir2msgstr -h
.bgforge.yml not found, assuming defaults
usage: dir2msgstr [-h] [--auto] [-s SRC_DIR] [-o OUTPUT_FILE] [--ext FILE_EXT] [--same] [--overwrite]

Load strings from files in selected dir into PO msgstr's

options:
  -h, --help      show this help message and exit
  --auto          automatically find POs and language dirs, process all valid extensions (default: False)
  -s SRC_DIR      directory to load (default: .)
  -o OUTPUT_FILE  existing PO file (default: None)
  --ext FILE_EXT  load files with this extension (default: None)
  --same          load translations that are identical to original strings (default: False)
  --overwrite     overwrite existing translations (default: False)
```

I don't see an action run in your fork though.

**Comment by abalabokhin** [comment]
Oh, was able to update russian.po file (added to the pull request). If I run `./dir2msgstr.py --auto ` from tra folder, it didn't update existing translation lines, only added new ones. So, I have to delete russian.po file and create a new one from english.pot. After running dir2msgstr again, I got russian.po file with all the actual lines.

Can you review my pull request (https://github.com/BGforgeNet/bg2-tweaks-and-tricks/pull/70) and let me know if something else needs to be done, please?

**Comment by burner1024** [comment]
> it didn't update existing translation lines, only added new ones

Which is that `--overwrite` option for. Try with it.

Why is action not run in your fork, anyway?

**Comment by abalabokhin** [comment]
Updated the pull request with russian.po file created with `--overwrite` option. 

> Why is action not run in your fork, anyway?

I know nothing about actions and how they should work. I created fork with clicking "Fork" icon, then cloned the repo to my PC, changed files locally, commit, push. To create pull request I use github. I don't know what is action and at what point it should run.

**Comment by burner1024** [comment]
Ah, they [disabled](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflows-in-forked-repositories-1) actions in forks by default, you'd have to enable them explicitly to get to run.

**Comment by burner1024** [comment]
I added a bunch of comments, there's probably more. I think the changes need to be proofed.

**Comment by abalabokhin** [comment]
Oh, you know Russian. I knew it was a bad idea trying to send somebody's else translation. I don't have enough time to proof read by myself, I will try to contact Ulpian (the author of translation) for that.

**Comment by burner1024** [comment]
If you do file-based translation in future, probably better to work with PO files directly, with POedit or something. It's less error-prone.
