### ISSUE TITLE
Component Limited stock doesn't work in current master and in 8.24 release

### ISSUE THREAD

**Issue by abalabokhin** [BGforgeNet/bg2-tweaks-and-tricks#72]
I tried to install the mod with Russian (I don't think it works with English though, but I didn't check), all the components installed fine but "Limited stock" one. See the copied from SETUP-TNT.DEBUG:

```
Install Component [Limited stock]?
[I]nstall, or [N]ot Install or [Q]uit? 
Installing [Limited stock] [v8.24]
Clearing the arrays.
Clearing the variables.
Clearing the inlined files.
Clearing the macros.
Clearing the IDS map.
[*.IDS] forgotten
[*.IDS] forgotten
Appending to files ...
Not appending [  0 ANYONE...] to [ea.ids] because it DOES contains [ANYONE]
[*.IDS] forgotten
Appending to files ...
Not appending [0x80101FEF CD_STATE_NOTVALID...] to [state.ids] because it DOES contains [CD_STATE_NOTVALID]
Clearing the IDS map.
[*.IDS] forgotten
Copying and patching 167 files ...
Copying and patching 1 file ...
Copied [misc16.itm] to [override/misc16.itm]
Copying and patching 1 file ...
Copied [misc17.itm] to [override/misc17.itm]
Copying and patching 1 file ...
Copied [misc18.itm] to [override/misc18.itm]
Copying and patching 1 file ...
Copied [misc19.itm] to [override/misc19.itm]
[./override/BAG02G.STO] loaded, 168 bytes
[./override/BAG02H.STO] loaded, 168 bytes
[./override/BAG02I.STO] loaded, 168 bytes
[./override/BAG19.STO] loaded, 1600 bytes
Copying and patching 1 file ...
[./override/arow11.itm] loaded, 218 bytes
override/arow11.itm copied to tnt/backup/59/arow11.itm, 218 bytes
Copied [arow11.itm] to [override/arow11.itm]
Copying and patching 1 file ...
[./override/bolt06.itm] loaded, 218 bytes
override/bolt06.itm copied to tnt/backup/59/bolt06.itm, 218 bytes
Copied [bolt06.itm] to [override/bolt06.itm]
Copying and patching 1 file ...
Copied [potn52.itm] to [override/potn52.itm]
Copying and patching 1 file ...
Copied [scrl1h.itm] to [override/scrl1h.itm]
Copying and patching 1 file ...
Copied [scrl1f.itm] to [override/scrl1f.itm]
Copying and patching 1 file ...
Copied [scrl2b.itm] to [override/scrl2b.itm]
Copying and patching 1 file ...
Copied [scrl1t.itm] to [override/scrl1t.itm]
Copying and patching 1 file ...
Copied [scrl2h.itm] to [override/scrl2h.itm]
Copying and patching 1 file ...
Copied [scrl7s.itm] to [override/scrl7s.itm]
Copying and patching 1 file ...
Copied [scrl6u.itm] to [override/scrl6u.itm]
Copying and patching 1 file ...
[./override/dart02.itm] loaded, 218 bytes
override/dart02.itm copied to tnt/backup/59/dart02.itm, 218 bytes
Copied [dart02.itm] to [override/dart02.itm]
Copying and patching 1 file ...
Copied [sw1h09.itm] to [override/sw1h09.itm]
Copying and patching 1 file ...
Copied [sw1h41.itm] to [override/sw1h41.itm]
Copying and patching 1 file ...
Copied [sw1h42.itm] to [override/sw1h42.itm]
Copying and patching 1 file ...

ERROR locating resource for 'COPY'
Resource [sw2h20.itm] not found in KEY file:
	[./chitin.key]
Stopping installation because of error.
ERROR: [BAG19.STO] -> [override/BAG19.STO] Patching Failed (COPY) (Failure("resource [sw2h20.itm] not found for 'COPY'"))
Stopping installation because of error.
Stopping installation because of error.
```

**Comment by burner1024** [comment]
What platform is it?
Fresh game or with some mods?

**Comment by abalabokhin** [comment]
It was bg1ee + sod + DLCMerge + couple of mods. I just tried with clear bg1ee (English) +  tnt (English) - error is the same. (The item is different, though: `ERROR: [BAG19.STO] -> [override/BAG19.STO] Patching Failed (COPY) (Failure("resource [scrl7s.itm] not found for 'COPY'"))`) My system is Linux, using wine, but somebody already complained about this component on Windows as well. I also checked with other versions of tnt - 8.20 works fine, but all the next versions (8.21-8.24) has the same error.

**Comment by burner1024** [comment]
I see. That's an issue with the games, then. Non-existent items are referenced in bags. Either the items or the bags have to be removed.
You should report this to wherever EE bugs go now.

It didn't show up in Golem, because Happy cleans up these issues. If it happens more often, I might consider doing both Happy enabled and disabled builds.

For the time being, I added a guard against this kind of issue.

**Comment by abalabokhin** [comment]
I don't think they are going to fix anything in EE. With the new code the ERROR is still here, but it is different:
```
Non-existent item scrl7s is referenced in store scrl2h
ERROR: cannot convert magical_scrl7s or %magical_scrl7s% to an integer
ERROR: [BAG19.STO] -> [override/BAG19.STO] Patching Failed (COPY) (Not_found)
```

**Comment by burner1024** [comment]
I don't see why assume when one can know. And even if they weren't going to fix anything, doesn't mean it shouldn't be reported. But maybe that's just me.

I added another change for this, hopefully it should be enough.

**Comment by abalabokhin** [comment]
Worked this time with lots of warnings like `Non-existent item helm24 is referenced in store arow15`. Thank you! 

For reporting bugs - my reasoning is simple: I don't have time for the bug reporting assuming it is never going to be fixed. I don't understand the issue well enough, so I need to spend some time understanding what the issue is and how to  describe it properly. 

I hope you can issue the new release soon with proper Russian translation and the fixed component.

**Comment by burner1024** [comment]
I'll make a release once I figure out the encoding situation.

**Comment by burner1024** [comment]
This component likely shouldn't need to process bags at all, so I skipped container types, and with that I think the amount of warnings should go down considerably.
