### ISSUE TITLE
Smarter Familiars component not working on EET, no other familiar-based mods installed AFAIK

### ISSUE THREAD

**Issue by catalystshift** [BGforgeNet/bg2-tweaks-and-tricks#74]
[WeiDU.log](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/11238589/WeiDU.log)
[Setup-tnt.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/11238602/Setup-tnt.zip)
Attached a zipped up setup-tnt debug file and my weidu.log. Not sure what else is required. 

I tried uninstalling resilient familiars in case I had misunderstood how the two components interacted but that didn't make a difference. Tried multiple new games and also tried different familiars by changing alignment on each new game, no new dialogue options show up and default dialogues work fine(petting or asking it to hop into backpack). 
Game is installed on an external HDD so I doubt its C: shenanigans. 

Lmk what else I can provide.
EDIT:
This is on the latest version of the mod via Releases section. Latest version of Baldur's Gate and every other mod installed is the latest version I could find.

**Comment by burner1024** [comment]
Could you run `weidu --change-log spwi123.spl` and see that it says? The `Mods affecting` section.

**Comment by catalystshift** [comment]
Sorry for taking so long. This what I got, assuming I ran it right:
Mods affecting SPWI123.SPL:
00000: /* created or unbiffed */ ~EET\EET.TP2~ 0 0 // EET core (resource importation)V13.4

**Comment by burner1024** [comment]
No changes. Well, maybe they have different dialogs for familiars in BGEE. I'll need to check.

**Comment by catalystshift** [comment]
Gotcha, lmk if I can run anything else, will do what I can! Just note I am a newbie at Baldur's Gate stuff haha.

**Comment by burner1024** [comment]
are you familiar with near infinity?

**Comment by catalystshift** [comment]
I have the program and have looked through it a bit, newbie at it. What do you need?

**Comment by burner1024** [comment]
Well EET crashes on my system, so I can't check myself.
Open your save and see which cre and dlg does your familiar use. I suspect EET changes `fampsd` to `fampsd_` or something.
![Captura desde 2023-04-15 21-38-01](https://user-images.githubusercontent.com/1279852/232230989-4c3bd783-d947-45f3-aa0b-247de9056256.png)
![Captura desde 2023-04-15 21-38-54](https://user-images.githubusercontent.com/1279852/232230992-1bab566b-66d5-487d-a88f-2fcec3469982.png)

**Comment by catalystshift** [comment]
Assuming I am in the right section, these seem to be the .cre+.dlg files, from opening up the Familiar Info section in my savegame:
FAMPSD.CRE - FAMIL1.DLG
FAMPSD25.CRE - FAMIL125.dlg
FAMPSD_.CRE - FAMIL1_.dlg
FAMQUAS.cre - FAMIL2.DLG
FAMQUA25.cre - FAMIL225.dlg
FAMQUAS_.cre - FAMIL2_.DLG
FAMRAB.cre - FAMIL3.DLG
FAMRAB25.cre - FAMIL325.DLG
FAMRAB_.cre - FAMIL3_.DLG
FAMRAD.CRE(not a familiar?) - ???? Doesn't have a dialogue script.
FAMWAR.cre(don't think this is a familiar...?) - no .dlg again.
FAMCAT.cre - FAMIL3.DLG
FAMCAT25.cre - FAMIL325.DLG
FAMCAT_.cre - FAMIL3_.DLG
FAMDOG.cre(jeez, is this leftover code lmao) - non.
FAMDUS25.cre - FAMIL225.DLG
FAMDUST.cre - FAMIL2.DLG
FAMDUST_.cre - FAMIL2_.DLG
FAMFAI25.cre - FAMIL125.DLG
FAMFAIR.cre - FAMIL1.DLG
FAMFAIR_.cre - FAMIL1_.DLG
FAMFER.cre - FAMIL3.DLG
FAMFER25.cre - FAMIL325.DLG
FAMFER_.cre - FAMIL3_.DLG
FAMFIRE.cre - none.
FAMIMP.cre - FAMIL2.DLG
FAMIMP25.cre - FAMIL225.DLG
FAMIMP_.cre - FAMIL2_.DLG
FAMLIGHT.cre - none.
FAMMIST.cre - none.

**Comment by burner1024** [comment]
No, don't need familiar info, that's just a list of all. Need your specific familiar cre name and dlg name.

**Comment by catalystshift** [comment]
...er, where can I find that? I have tried checking 'Party member 0' but don't think its there.
Unless you meant which familiar I am using in general, think that would be these:
FAMPSD.CRE - FAMIL1.DLG
FAMPSD25.CRE - FAMIL125.dlg
FAMPSD_.CRE - FAMIL1_.dlg
Its a pseudo-dragon.

In case this is faster/more helpful, here is the save game in question.

[000000001-Sight-Quick-Save.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/11239987/000000001-Sight-Quick-Save.zip)

**Comment by burner1024** [comment]
I don't see a summoned familiar in this save.

**Comment by catalystshift** [comment]
*headdesk* yep, yep you are correct. I never saved post summoning and only kept a save pre-summon. Sorry about that!
[000000001-Sight-Quick-Save-3.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/11240178/000000001-Sight-Quick-Save-3.zip)
This should have it. Going to go ahead and try exploring it again myself as well ;v;b

**Comment by burner1024** [comment]
Right, it's a `fampsd_` with `famil1_.dlg`.
I think it's a version designed for bg1 part only, somehow EET keeps them separate.
I'll need to add support for this.

**Comment by catalystshift** [comment]
That made me remember, I looked through issues from before and found this:
https://github.com/BGforgeNet/bg2-tweaks-and-tricks/issues/64
"-Enhanced Edition Trilogy AKA EET (https://github.com/Gibberlings3/EET/releases)
EET changes familiars to accommodate casters of all levels."
If EET keeps it game specific then there's likely a SoD version as well alongside the obvs BG2EE version.

Anyway, glad I managed to contribute however minor! And ty for the mod in general! :3

**Comment by burner1024** [comment]
There, if you download [this file](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/blob/master/tnt/lib/familiars.tpa) and replace the corresponding one in your local tnt dir, then reinstall the component, you should be able to see new dialog options.

**Comment by burner1024** [comment]
attach the file that you've downloaded

**Comment by catalystshift** [comment]
[familiars.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/11242333/familiars.zip)
I right-clicked the file from /lib and saved it if that makes a differences for some reason.

**Comment by catalystshift** [comment]
I am looking at the file in notepad++, and now I have learned to do so as part of my troubleshooting. I am pretty sure this isn't a proper download. Let me retry from scratch!

**Comment by catalystshift** [comment]
![Baldr000](https://user-images.githubusercontent.com/78179142/232313785-6ba7939e-6c6d-437e-8d04-0fa6db4fa76f.png)
Looks like it worked perfectly! At least as far as I can tell!

Slightly paranoid that NPC_EE or EET End didn't appear in my weidu cmd while installing this, so ima just redo the whole install still lol.

**Comment by burner1024** [comment]
You mean they don't work?

**Comment by catalystshift** [comment]
Sorry, I may have put it in a confusing way. Let me try rephrasing/rewriting here:

- On old saves, after reinstalling the component, the dialogue changes show up but none of the functions actually work. Eg: familiar does not follow after setting the new distance/speed options.
This is a minor thing because everything works perfectly on a new character and thus a new save.

- The reinstall thing was me being extraneous, sorry. All I said was WeiDU didn't seem to remove NPC_EE and EET End before installing the familiar components which seemed odd to me so I am going to reinstall the whole thing soon to be safe. In the meantime, before I do that, I went ahead and tested the mod on the old character Sight where functions didn't work and then a new character where it worked fine, no issues.

I can be too detailed for my own good sometimes. Lmk if I am still somehow unclear haha.

**Comment by burner1024** [comment]
Ah, yes, the original familiars have no scripts by default, so you'd have to restart game or at least re-summon the familiar for it to work.

**Comment by catalystshift** [comment]
You are correct, went back to the Sight save and killed and resummoned the Familiar and I can confirm the follow script works fine, and thus I am assuming the rest! Makes this a lot easier for anyone installing this midgame then \o/

**Comment by burner1024** [comment]
I guess this is fixed, and the last isssue is in #75. If not, let me know.
