### ISSUE TITLE
Smarter Familiars: Familiar does not show in inventory if put in bag or respawn when "come out of bag when combat is over/no enemies are around" is selected.

### ISSUE THREAD

**Issue by catalystshift** [BGforgeNet/bg2-tweaks-and-tricks#75]
- Familiars disappear from inventory/don't show up when told to come out of bag post combat, even if put in bag manually after selecting that option. 
- They are treated as still existing, meaning the spell Find Familiar doesn't work because the game thinks your familiar is still alive.
[000000046-Option selected, familiar gone.zip](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/files/11242587/000000046-Option.selected.familiar.gone.zip)

This is post the familiars.tpa updated file and on an EET install and a new game.
EDIT:
Save file with the disappeared familiar uploaded.

**Comment by burner1024** [comment]
So, what exactly happens? You press "release familiar", and the familiar doesn't appear?

**Comment by catalystshift** [comment]
Nope. There is no familiar in the inventory at all. So nothing I can click on to bring up the familiar window even.
There was one instance where I noticed the familiar staying in the inventory for a second or two but disappeared again as soon as I closed the screen and unpaused, not sure how to replicate that one.

...I also just noticed I failed to mention I am using Dragonspear UI++, an interaction with that maybe? Although I don't see how because its just this particular script option('leave bag after combat') its happening with, familiar shows up within inventory fine without it.

**Comment by burner1024** [comment]
Does it appear in inventory correctly if you uninstall the mod and start a new game?

**Comment by catalystshift** [comment]
I am fairly certain it should, but worth a check. Will have this is edited within an hour and half of posting, gimme a few.
The error with the mod at least only happens when I have "automatically jump out of pack after combat ends" selected, otherwise it doesn't. Anyway, brb, gonna check just in case.

**Comment by burner1024** [comment]
So I finally was able to get EET to launch, did some tests and I can't reproduce.
I'll need more detailed steps, and/or a video, starting from summoning a familiar.
And no cheated characters, please.

**Comment by burner1024** [comment]
No, I made a mistake, it's reproducible.

**Comment by burner1024** [comment]
Should be working now.
