### ISSUE TITLE
How can I add female replicas using this translation system?

### ISSUE THREAD

**Issue by abalabokhin** [BGforgeNet/bg2-tweaks-and-tricks#76]
Hi, I was thinking about updating Russian translation for Ascension (sorry for asking here, I cannot create issues in the Ascension repo) using the translation system (https://hive.bgforge.net/projects/infinity-engine/ascension/), but haven't found a UI element for female replicas. For tra files, it looks like: 
`@X = ~male replica~ ~female replica~`

**Comment by burner1024** [comment]
You can ask on the [forum](https://forums.bgforge.net/).
Female translation is explained [here](https://forums.bgforge.net/viewtopic.php?f=9&t=28).
