### ISSUE TITLE
For classic BG2 tra_ee is used for translation

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/bg2-tweaks-and-tricks#78]
I'm installing TnT on classic BG2 with an edited component description that shows the location of the string:
```
E:\Gry-IE\BG2>Setup-tnt.exe --language 1 --force-install-list 0
[Setup-tnt.exe] WeiDU version 24900
Using Language [Polish]

Installing [Smarter familiars - tra_ee - polish] [v8.26]
Clearing the arrays.
Clearing the variables.
Clearing the inlined files.
Clearing the macros.
Clearing the IDS map.
Appending to files ...
Appending to files ...
Clearing the IDS map.
loading 1 tra file
...
```
As you can see `@910` is taken from `tra_ee\polish`.

I'm not quite sure what are you doing with the HANDLE_CHARSET alternative but the best way to have one, unified translation directory is to have *.tra files as UTF8 and use from_utf8 = 1.

**Comment by burner1024** [comment]
That's ok.
