### ISSUE TITLE
Project Infinity Saving Components

### ISSUE THREAD

**Issue by arosenow** [BGforgeNet/bg2-tweaks-and-tricks#79]
Hi, as all your components aren't currently labelled they reset to blank on Project infinity because it only remembers components the ones with a LABEL after the BEGIN. 

My solution for a lot of mods is I made an autopatcher, but it appears you intend to make it compatible as you'd already began labelling

**Comment by arosenow** [comment]
Yeah, my autopatcher just takes any mod that hasn't been labelled and puts temp labels in so that it's compatible, as realistically I'm only going to run this exact install once and I'm not likely to update a mod as it will corrupt my saves. I may have to just extend it to also patch mods that have been started but not all are labelled. Can empathise

**Comment by burner1024** [comment]
Generally speaking, I'm not opposed to labeling, but I'm not going to drag those labels forever.
Should you want to submit a PR with additional labels, that should be fine.

**Comment by arosenow** [comment]
The requirements for permanent labels on all mods limits the utility of project infinity a lot, that's why I made my tool to automate patching the hundreds of mods that don't have them. If I were a proper coder and not a statistician I wouldn't have written it in R :-P Although it's surprisingly good with strings etc
