### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by abalabokhin** [BGforgeNet/bg2-tweaks-and-tricks#82]
There are also some troubles with the lastest version of the mod. Unfortunately, I am not the one who found the issues, so I might not be able to give lots of details, but I will do my best.

1. While installing on eet, the component "No talking when hiding in shadows" ether freezes or work very slow (he waited 15 minutes for it to finish and then stopped the installation process).
2. After installing the mod, there are some wierdly combined lines in dialog.tlk for Russian language. I understand, it probably works ok in English, but on other languages (at least Russian) it might looks wierd. The examples are:
```
Задержанный взрыв огненного шара ловушка
Слово силы, Усыпить ловушка
```
It is probably should be at least \~Ловушка "Задержанный взрыв огненного шара"\~ or something like that.
3. Also during the installation, there is a string with "Invalid Strref -1": 
```
[./override/METR001.SPL] loaded, 538 bytes
found gaze pro: METR001 - <Invalid Strref -1>
[./override/METR003.SPL] loaded, 202 bytes
```
that might indicates a bug.

**Comment by burner1024** [comment]
>  While installing on eet, the component "No talking when hiding in shadows" ether freezes or work very slow (he waited 15 minutes for it to finish and then stopped the installation process).

It's a [very simple](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/blob/master/tnt/components/no_talk_shadows/main.tpa) component, and problems with it probably indicated problems with the game.
The whole mod [takes](https://golem.bgforge.net/logs/tweaks-and-tricks/583) 5-10 minutes to install.
If you wish to debug it, should be easy to add some PATCH_PRINT SOURCE_FILE to see where it gets stuck, if it does.

>  After installing the mod, there are some wierdly combined lines in dialog.tlk for Russian language.

Made a change for that.

>  Also during the installation, there is a string with "Invalid Strref -1":

Not a bug.
