### ISSUE TITLE
Improved Equalizer issues

### ISSUE THREAD

**Issue by dbazanov** [BGforgeNet/bg2-tweaks-and-tricks#84]
For some reason Cromwell was asking 12500 price for forging multiple items, that have 7500 set as price in wiki
I've done some investigation and ended up at this mod
1) It sets 12500 price to state 54 response, which I assume means that price for equalizer forging is changed to 12500, which is not documented
2) This state is shared by multiple other items in dialogue tree, e.g. Shortbow of Gesen and Silver Blade, which changes their price to 12500, which I assume is not the intended action

It's a small issue, just wanted to bring to your attention

**Comment by burner1024** [comment]
It sure isn't supposed to change other items prices. Thanks for investigation.
