### ISSUE TITLE
NPC voicesets

### ISSUE THREAD

**Issue by arosenow** [BGforgeNet/bg2-tweaks-and-tricks#85]
Hi, Imoens voiceset changes substantially in the sequel for plot reasons to be more pessimistic/traumatised. Extending her soundset to use the sequels doesn't fit with the BG1 soundset/story

**Comment by burner1024** [comment]
Don't install it then?

**Comment by arosenow** [comment]
That is my default position currently, however it is an issue to have Imoen talk about trauma that hasn't happened yet in BG1 given it's an EET mod. It can easily be remedied by excluding Imoen from that component, or making npcs modular

**Comment by burner1024** [comment]
If you have specific lines in mind, please list them.

**Comment by arosenow** [comment]
Imoen: Just like old times. Well, except for the torture and all.

**Comment by burner1024** [comment]
Just this one?
