### ISSUE TITLE
Can't install Working Non-Detection on a SoD game, tnt 8.30

### ISSUE THREAD

**Issue by AshLancer** [BGforgeNet/bg2-tweaks-and-tricks#86]
Hello again,

I'm not sure what's going on, but when I try to install the Working Non-Detection component on my SoD game, the mod just skips over it saying "Non-Detection spell is not present in game". This makes no sense, since vanilla SoD does have a SPWI310.SPL (Non-Detection) file in the resources. Only when I open tnt.tp2 and comment out the line REQUIRE_PREDICATE FILE_EXISTS_IN_GAME ~ %WIZARD_NON_DETECTION%.spl ~, then I'm suddenly able to install the component without issue.

**Comment by burner1024** [comment]
8.30 installs on SoD [fine](https://golem.bgforge.net/logs/tweaks-and-tricks/631).
Probably something's different about your installation. Provide details.

**Comment by AshLancer** [comment]
I do not know. This is a clean SoD downloaded off Beamdog's store using their client. Running Windows 10. I use ProjectInfinity for ease-of-use in my installation and all it says is _Non-Detection spell is not present in game_.:

![Untitled999](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/assets/42629680/1b11dbd9-36d0-484e-b895-9b5a30a96355)

As a test, I tried to install other components that use the REQUIRE_PREDICATE FILE_EXISTS_IN_GAME check for spells in the .tp2 file, such as Unstack Chaos Shield or Uncheese Mislead. They both refuse to install and print their respective messages. But Uncheese Project Image DOES install.

![Untitled998](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/assets/42629680/befb5ee1-f4e3-4c51-a214-63a87e0d5b6d)

My only theory is that this call doesn't work with spell IDS names? Maybe it should instead refer to the SPL file itself.

**Comment by burner1024** [comment]
Logs please. Weidu log, install log.
