### ISSUE TITLE
Trap reminders makes a chest inaccessible

### ISSUE THREAD

**Issue by comiluv** [BGforgeNet/bg2-tweaks-and-tricks#87]
# Description
In Irenicus' Dungeon where Baldur's Gate SOA starts, there's a trapped chest in the chamber south of dryads. With "trap reminders" component installed, the chest becomes inaccessible as the position to access it is blocked

# Steps to reproduce the issue
1. Select "Trap reminders : disclose trap type" and "Improved trap detection: core"
2. Start a new game in Baldur's Gate 2 EE
3. Proceed to the chamber south of dryads
4. Click on the chest next to the bed
5. See error

# Screenshot
https://github.com/BGforgeNet/bg2-tweaks-and-tricks/assets/19642705/de56d435-6cd0-4df0-8845-f9b563d7cece

# Additional info
tnt version 8.31
BG2EE version 2.6.6.0 steam
Selecting "Trap reminders: generic" also causes the error

# weidu.log
```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~TNT/TNT.TP2~ #0 #4 // Trap reminders -> disclose trap type: v8.31
~TNT/TNT.TP2~ #0 #14 // Improved trap detection: core (REQUIRED for any of previous traps components to work): v8.31
```

**Comment by burner1024** [comment]
Crap =/. 8.31 was supposed to fix that.
Did you start a fresh game after installing 8.31?

**Comment by comiluv** [comment]
> Did you start a fresh game after installing 8.31?

Yes

**Comment by burner1024** [comment]
I can't seem to reproduce.
Any more details?
![Captura desde 2024-03-09 18-37-09](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/assets/1279852/84114a7c-d1f2-40b3-97ae-eef3a5793fde)
![Captura desde 2024-03-09 18-37-23](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/assets/1279852/acb9e23b-1e8e-41bb-b21f-24b91da16b39)

**Comment by comiluv** [comment]
Did you install "Trap reminders" component? Because I'm not seeing any trap reminders in your screenshots

**Comment by burner1024** [comment]
Of course.
![Captura desde 2024-03-09 19-24-48](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/assets/1279852/ceedf96e-aabd-4c89-b0c4-4c188b872cea)

**Comment by comiluv** [comment]
I tested again after running check integrity on installed Baldur's Gate 2 EE from steam and failed to reproduce the issue with 8.31 Maybe updating on previous version doesn't work? Anyway closing this issue as `can't repro`

**Comment by burner1024** [comment]
It wouldn't work on already visited areas, but should be fine in new ones.
Not sure exactly what is going on, but let me know if you run into this again.

I also don't like how fast reminders disappear. EEs seem to work a bit differently. This could probably use more tweaking.
