### ISSUE TITLE
Unresolved entry in tracking.2da

### ISSUE THREAD

**Issue by MikeX1234** [BGforgeNet/bg2-tweaks-and-tricks#88]
From tracking.2da (BGT game):
...
%IsleofBalduran% O_137027
...

'IsleofBalduran' does not exits, there is either 'IsleofBalduranN' or 'IsleofBalduranS'

So line 99 in in main.tpa should probably changed...

**Comment by burner1024** [comment]
You're right. Too bad EVAL doesn't emit an error when there's nothing to eval.

**Comment by MikeX1234** [comment]
Thank you!
